/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat */
        post: operations["post_chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Papers */
        get: operations["list_papers_api_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Paper */
        get: operations["get_paper_api_papers__paper_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Facets */
        get: operations["get_facets_api_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/landing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Landing
         * @description The whole front page in one call — it is one static composition.
         *
         *     `limit` defaults to `frontier_top_cited` because that setting IS the
         *     manifest select_frontier.py indexed against: a smaller default would
         *     silently hide foundations whose papers we fetched, chunked and embedded,
         *     and a larger one would list foundations with no indexed citers behind them.
         */
        get: operations["get_landing_api_landing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foundations/{arxiv_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foundation */
        get: operations["get_foundation_api_foundations__arxiv_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Latest
         * @description The dashboard's "what just landed" list — newest indexed papers.
         */
        get: operations["get_latest_api_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description How much of each month we hold — the provenance panel's whole input.
         */
        get: operations["get_coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Session Id */
            session_id?: string | null;
            /** Foundation Id */
            foundation_id?: string | null;
        };
        /** CitedExcerpt */
        CitedExcerpt: {
            /** Chunk Id */
            chunk_id: string;
            /** Section */
            section: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Text */
            text: string;
        };
        /** CitedYearBucket */
        CitedYearBucket: {
            /** Year */
            year: number | null;
            /** Citations */
            citations: number;
        };
        /** CoCitedWork */
        CoCitedWork: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string | null;
            /** Version */
            version: string | null;
            /** Cite Both */
            cite_both: number;
        };
        /**
         * CohortStats
         * @description What the page opens with: the cohort it counted, and how complete it is.
         *
         *     There is no "window" here any more, and that is the point. The window was
         *     `min/max(citing id-month)`, which 261 old seed papers (1.5% of the citing
         *     side) stretched from two months to nineteen years, and every sentence
         *     hanging off it then claimed we hold "every cs paper arXiv posted" across
         *     that span. We hold 94% of July 2026, 49% of August, 5% of September and
         *     under 2% of everything else.
         *
         *     So the cohort is stated as what it is, with its own denominator beside it:
         *     `cohort_catalog_papers` is what the catalog lists for those same months
         *     (`catalog_months`), and it is None when the snapshot is older than the
         *     cohort and therefore cannot answer.
         *
         *     Every field here is one a reader has a use for: how much of arXiv this
         *     counted, what came out of it, and how much of it the agent can actually
         *     read. Stage counts that only describe our pipeline do not belong on the
         *     wire — `papers_parsed` is the sole survivor of that kind, and only
         *     because the parse rate the methods note states is a percentage of it.
         */
        CohortStats: {
            /** Cohort Start */
            cohort_start: string | null;
            /** Cohort End */
            cohort_end: string | null;
            /** Cohort Papers */
            cohort_papers: number;
            /** Cohort Catalog Papers */
            cohort_catalog_papers: number | null;
            /** Papers Parsed */
            papers_parsed: number;
            /** Papers With References */
            papers_with_references: number;
            /** Citations */
            citations: number;
            /** Cited Works */
            cited_works: number;
            /** Readable Papers */
            readable_papers: number;
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Months */
            months: components["schemas"]["MonthBucket"][];
        };
        /** FacetBucketOut */
        FacetBucketOut: {
            /** Value */
            value: string | number | null;
            /** Count */
            count: number;
        };
        /** FacetDimension */
        FacetDimension: {
            /** Buckets */
            buckets: components["schemas"]["FacetBucketOut"][];
            /** Truncated */
            truncated: boolean;
        };
        /** FacetsResponse */
        FacetsResponse: {
            /** Total */
            total: number;
            category: components["schemas"]["FacetDimension"];
            year: components["schemas"]["FacetDimension"];
            license: components["schemas"]["FacetDimension"];
            venue: components["schemas"]["FacetDimension"];
        };
        /**
         * Foundation
         * @description A work our recent cohort builds on. Not a `papers` row — see cited_works.
         */
        Foundation: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string | null;
            /** Authors */
            authors: string | null;
            /** Primary Category */
            primary_category: string | null;
            /** Year */
            year: number | null;
            /** Version */
            version: string | null;
            /** Cited By */
            cited_by: number;
        };
        /** FoundationDetailResponse */
        FoundationDetailResponse: {
            foundation: components["schemas"]["Foundation"];
            /** Co Cited */
            co_cited: components["schemas"]["CoCitedWork"][];
            /** Indexed Citers */
            indexed_citers: components["schemas"]["IndexedCiter"][];
            /** Total Citers */
            total_citers: number;
            /** Scope Size */
            scope_size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IndexedCiter
         * @description A citing paper we hold and have indexed — every one of these opens.
         */
        IndexedCiter: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Primary Category */
            primary_category: string;
            /** Version */
            version: string | null;
        };
        /** LandingResponse */
        LandingResponse: {
            stats: components["schemas"]["CohortStats"];
            /** Foundations */
            foundations: components["schemas"]["Foundation"][];
            /** Cited Years */
            cited_years: components["schemas"]["CitedYearBucket"][];
        };
        /**
         * LatestPaper
         * @description A paper we hold and have indexed, newest first. Indexed-only (D16):
         *     the dashboard links every row to the reader, so nothing listed may
         *     dead-end. Fresh-but-unindexed papers appear here on their own once the
         *     index run covers them — no second code path.
         */
        LatestPaper: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string | null;
            /** Primary Category */
            primary_category: string | null;
            /** Published */
            published: string;
            /** Version */
            version: string | null;
            /** Ref Count */
            ref_count: number;
        };
        /** LatestResponse */
        LatestResponse: {
            /** Papers */
            papers: components["schemas"]["LatestPaper"][];
        };
        /**
         * MonthBucket
         * @description One id-month of the corpus, against what arXiv posted that month.
         *
         *     `catalog_papers` is the whole reason this shape exists. Bar heights of
         *     what we hold, with no denominator, said "19 papers in October 2025" on a
         *     page about what CS is building on, and a reader takes that as a fact about
         *     October rather than about our download schedule. It is None when the
         *     catalog snapshot cannot answer for that month (it lists fewer papers than
         *     we hold, i.e. the snapshot predates the month) — unknown is printable,
         *     a wrong denominator is not.
         *
         *     Keyed by ID-MONTH, not by `published`: the census counts id-months, and
         *     the two disagree by 383 papers for July 2026 alone (arXiv announces a
         *     late-June submission with a 2607 id), which would put the numerator and
         *     denominator of the same bar on different axes.
         */
        MonthBucket: {
            /** Month */
            month: string;
            /** Papers Held */
            papers_held: number;
            /** Papers Parsed */
            papers_parsed: number;
            /** Refs Made */
            refs_made: number;
            /** Catalog Papers */
            catalog_papers: number | null;
        };
        /** PaperDetailResponse */
        PaperDetailResponse: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string;
            /** Abstract */
            abstract: string;
            /** Categories */
            categories: string;
            /** Primary Category */
            primary_category: string;
            /** Year */
            year: number;
            /** Published */
            published: string;
            /** Venue */
            venue: string | null;
            /** License */
            license: string | null;
            /** Version */
            version: string | null;
            /** Facets */
            facets: {
                [key: string]: number | null;
            };
            /** N Chunks */
            n_chunks: number;
            /** Excerpts */
            excerpts: components["schemas"]["CitedExcerpt"][];
            /** Excerpts Truncated */
            excerpts_truncated: boolean;
        };
        /** PaperListItem */
        PaperListItem: {
            /** Arxiv Id */
            arxiv_id: string;
            /** Title */
            title: string;
            /** Authors */
            authors: string;
            /** Abstract */
            abstract: string;
            /** Primary Category */
            primary_category: string;
            /** Year */
            year: number;
            /** Venue */
            venue: string | null;
            /** License */
            license: string | null;
            /** Version */
            version: string | null;
            /** Score */
            score: number | null;
            /** Facets */
            facets?: {
                [key: string]: number | null;
            } | null;
        };
        /** PapersResponse */
        PapersResponse: {
            /** Items */
            items: components["schemas"]["PaperListItem"][];
            /** Next Cursor */
            next_cursor: string | null;
            /** Total */
            total: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_papers_api_papers_get: {
        parameters: {
            query?: {
                q?: string;
                category?: string | null;
                year_from?: number | null;
                year_to?: number | null;
                facets?: string | null;
                sort?: ("relevance" | "year_desc" | "year_asc" | "title_asc") | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_paper_api_papers__paper_id__get: {
        parameters: {
            query?: {
                /** @description comma-separated chunk_ids for the capped cited-excerpt lookup */
                chunks?: string | null;
            };
            header?: never;
            path: {
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facets_api_facets_get: {
        parameters: {
            query?: {
                category?: string | null;
                year_from?: number | null;
                year_to?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_landing_api_landing_get: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_foundation_api_foundations__arxiv_id__get: {
        parameters: {
            query?: {
                co_cited_limit?: number;
                citers_limit?: number | null;
            };
            header?: never;
            path: {
                arxiv_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_latest_api_latest_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_coverage_api_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageResponse"];
                };
            };
        };
    };
}
